<?php

/**
 * @file
 * Contains webform_content_access.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function webform_content_access_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_content_access module.
    case 'help.page.webform_content_access':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provide the possibility to create private content accessible only after webform submit.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_field_access().
 */
function webform_content_access_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {
  $config = $config = \Drupal::config('webform_content_access.default');
  $fields_names = explode(',', str_replace(' ', '', $config->get('fields_to_lock')));
  $content_type = $config->get('content_type_to_lock');
  $node = \Drupal::routeMatch()->getParameter('node');

  if(in_array($field_definition->getName(), $fields_names) && $node !== null) {
    if($node->bundle() === $content_type) {
      $id_user = \Drupal::currentUser()->id();
      $id_content = $node->id();
      $database = \Drupal::database();

      $query = $database
        ->select('webform_content_access_track', 'wcat')
        ->condition('wcat.id_user', $id_user, '=')
        ->condition('wcat.id_content', $id_content, '=')
        ->countQuery()
        ->execute()
        ->fetchField();

      if($query <= 0) {
        return AccessResult::forbidden();
      }
    }
  }

  return AccessResult::neutral();
}